"""empty message

Revision ID: 23061db18d3f
Revises: 8a0bc5d2a79f
Create Date: 2019-12-17 00:40:52.025373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23061db18d3f'
down_revision = '8a0bc5d2a79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_user_hash_id', table_name='user')
    op.drop_column('user', 'hash_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash_id', mysql.VARCHAR(length=256), nullable=True))
    op.create_index('ix_user_hash_id', 'user', ['hash_id'], unique=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
