"""added price

Revision ID: aabd567bb658
Revises: 23061db18d3f
Create Date: 2019-12-17 01:32:11.088822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aabd567bb658'
down_revision = '23061db18d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('price', sa.Float(precision=2, asdecimal=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'price')
    # ### end Alembic commands ###
